name: Webtunnel Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g. v1.0.0)'
        required: true
      release_notes:
        description: 'Release Notes'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 允许创建 Release 并上传文件

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Tidy Go modules
      run: go mod tidy

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/webtunnel-server ./examples/servercli/server.go
        GOOS=linux GOARCH=amd64 go build -o dist/webtunnel-client ./examples/webtunclient/

    - name: Package binaries
      run: |
        cd dist
        tar -czvf webtunnel-${{ github.event.inputs.tag }}.tar.gz webtunnel-server webtunnel-client

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        body: ${{ github.event.inputs.release_notes }}
        files: |
          dist/webtunnel-${{ github.event.inputs.tag }}.tar.gz
