name: Webtunnel Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag (e.g. v1.0.0)'
        required: true
      release_notes:
        description: 'Release notes or description'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 用于创建 Release
      packages: write  # 如果你后续要上传到 GitHub Packages

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install Dependencies
      run: |
        go mod tidy

    - name: Build Server
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/server ./examples/servercli/server.go

    - name: Build Client
      run: |
        GOOS=linux GOARCH=amd64 go build -o dist/client ./examples/webtunclient/

    - name: Archive Build Artifacts
      run: |
        tar -czvf dist/webtunnel-${{ github.event.inputs.tag }}.tar.gz -C dist client server

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        body: ${{ github.event.inputs.release_notes }}
        files: |
          dist/webtunnel-${{ github.event.inputs.tag }}.tar.gz
